### ISSUE TITLE
Error `Can't import the named export 'Events' from non EcmaScript module`

### ISSUE THREAD

**Issue by kungfooman** [playcanvas/observer#4]
From this thread: https://forum.playcanvas.com/t/how-to-add-the-pcui-package-to-a-react-app/22289/4

I tested around with conditional exports in `package.json` first: https://nodejs.org/api/packages.html#packages_conditional_exports

```js
  "exports": {
    "import": "./index.mjs",
    "require": "./index.js"
  }
```

But then I realized `react-scripts` (using `webpack`) is ignoring that and I just had to remove those two lines to make it work:

https://github.com/playcanvas/playcanvas-observer/blob/6c1ae13c222e8c640252a25979e487c71a57d71f/package.json#L5-L6

Now it works for `require` and `import` case, `require` test via `node` itself:

![image](https://user-images.githubusercontent.com/5236548/136363386-69b4b46e-b7c6-4d5f-9aa2-27259cb8defd.png)

But I don't know if that breaks other setups, while it works with webpack... everybody is using a different bundler with different import rules and whatnot.

**Comment by willeastcott** [comment]
I believe this is now fixed. I added `publint` support to the repo today and it reports no problems. Closing.
